# Generated by Django 4.1.7 on 2023-02-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commute_Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('start_nick', models.CharField(max_length=50)),
                ('end_nick', models.CharField(max_length=50)),
            ],
        ),
    ]
