# Generated by Django 4.1.7 on 2023-03-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='driveScore',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='search',
            name='groceryScore',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='search',
            name='hospScore',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='search',
            name='overallScore',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='search',
            name='restScore',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
    ]
